const port = 3000;
const rootDir = "./",
      docs = rootDir + "docs/",
      docsCss = docs + "css/",
      docsJs = docs + "js/",
      docsAssets = rootDir + "docs-assets/",
      docsCssAssets = docsAssets + "css/",
      docsJsAssets = docsAssets + "js/",
      sassFolder = rootDir + "scss/",
      sassFiles = sassFolder + "**/*.scss",
      sassMain = sassFolder + "grid-system.scss",
      pugFolder = rootDir + "pug/",
      pugFiles = pugFolder + "**/*.pug",
      pugMain = pugFolder + "index.pug",
      cssFolder = rootDir + "css/",
      jsList = [
				'./node_modules/highlightjs/highlight.pack.min.js',
				docsJsAssets + "script.js",
      ],
      cssList = [
        './node_modules/highlightjs/styles/monokai-sublime.css',
        './css/grid-system.css',
        docsCssAssets + "style.css",
      ],
      specFiles = rootDir + "spec/**/*.[s|s]pec.js";

module.exports = {
  rootDir,
  docs,
  docsAssets,
  docsCss,
  docsJs,
  jsList,
  cssList,
  sassFolder,
  sassFiles,
  sassMain,
  cssFolder,
  pugFolder,
  pugFiles,
  pugMain,
  port,
  specFiles,
}