const port = 3000;
let rootDir = "./",
      docs = rootDir + "docs/",
      docsCss = docs + "css/",
      docsJs = docs + "js/",
      docsSass = docs + "scss/",
      docsCssFiles = docsCss + "**/*.css",
      docsJsFiles = docsJs + "**/*.js",
			docsSassFiles = docsSass + "**/*.s[c|a]ss",
			docsSassMain = docsSass + "style.scss",
			sassFolder = rootDir + "scss/",
      sassFiles = sassFolder + "**/*.scss",
      sassMain = sassFolder + "grid-system.scss",
      pugFolder = rootDir + "pug/",
      pugFiles = pugFolder + "**/*.pug",
      pugMain = pugFolder + "index.pug",
      cssFolder = rootDir + "css/",
      jsList = [
				'./node_modules/js-cookie/src/js.cookie.js',
				'./node_modules/highlightjs/highlight.pack.min.js',
      ],
      cssList = [
				'./node_modules/@fortawesome/fontawesome-free/css/all.min.css',
        './node_modules/highlightjs/styles/monokai-sublime.css',
        './css/grid-system.css',
      ];

module.exports = {
  rootDir,
  docs,
  docsCss,
	docsJs,
	docsCssFiles,
	docsJsFiles,
	docsSass,
	docsSassFiles,
	docsSassMain,
	jsList,
  cssList,
  sassFolder,
  sassFiles,
  sassMain,
  cssFolder,
  pugFolder,
  pugFiles,
  pugMain,
  port,
}